{
 "title": "AzSHCI - Storage Dashboard",
 "tags": [
  "windows",
  "hyper-v",
  "vm",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "SHOW TAG VALUES FROM \"win_system\" WITH KEY = \"clustername\""
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"win_system\" WITH KEY = \"host\""
   },
   {
    "name": "csv_volume",
    "label": "Cluster Volume",
    "query": "SHOW TAG VALUES FROM \"cluster_csv_filesystem\" WITH KEY = \"instance\" WHERE host =~ /$hostname/"
   },
   {
    "name": "virtual_machine",
    "label": "Virtual Machine",
    "query": "SHOW TAG VALUES FROM \"hyperv_vid\" WITH KEY = \"instance\" WHERE \"host\" =~ /^$hostname$/"
   },
   {
    "name": "vm_disk",
    "label": "VM Disk",
    "query": "SHOW TAG VALUES FROM \"hyperv_storage\" WITH KEY = \"instance\" WHERE \"host\" =~ /^$hostname$/"
   },
   {
    "name": "virtual_switch",
    "label": "Virtual Switch",
    "query": "SHOW TAG VALUES FROM \"hyperv_vswitch\" WITH KEY = \"instance\" WHERE host =~ /$hostname/"
   }
  ]
 },
 "panels": [
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Shared FS Performance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_instance read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster_csv_filesystem",
     "select": [
      [
       { "params": [ "Redirected_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
     ]
    },
    {
     "alias": "$tag_instance write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster_csv_filesystem",
     "select": [
      [
       { "params": [ "Redirected_Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Shared FS IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_instance reads/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster_csv_filesystem",
     "query": "SELECT sum(\"Reads_persec\") FROM \"cluster_csv_filesystem\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^$csv_volume$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(none)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
     ]
    },
    {
     "alias": "$tag_instance writes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster_csv_filesystem",
     "select": [
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS  IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance - Reads",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Reads_persec\") FROM \"cluster_csv_fs\" WHERE (\"instance\" =~ /^$csv_volume$/ AND \"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$tag_instance - Writes",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT \"Reads_persec\", \"Writes_persec\" AS \"Writes\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"instance\", \"host\"",
     "select": [
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS  IOPS Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Reads_persec\"), sum(\"Writes_persec\") FROM \"cluster_csv_fs\" WHERE $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ],
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host - DiskID: $tag_instance",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT max(\"Disk_Transfers_persec\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s), \"instance\", \"host\"",
     "select": [
      [
       { "params": [ "Disk_Transfers_persec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk IOPS Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$hostname Total IOPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT sum(\"Disk_Transfers_persec\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Disk_Transfers_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host - DiskID: $tag_instance",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT max(\"Avg._Disk_sec/Transfer\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^27|28|29|30|31|32/) AND $timeFilter GROUP BY time(10s), \"instance\", \"host\"",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Transfer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Throughput Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host - DiskID: $tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT \"Disk_Transfers_persec\" FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" > '2') AND $timeFilter GROUP BY \"instance\", \"host\"",
     "select": [
      [
       { "params": [ "Disk_Read_Bytes_persec" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Throughput Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host - DiskID: $tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT \"Disk_Transfers_persec\" FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" > '2') AND $timeFilter GROUP BY \"instance\", \"host\"",
     "select": [
      [
       { "params": [ "Disk_Write_Bytes_persec" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Write Latency",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 48 },
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster_csv_filesystem",
     "select": [
      [
       { "params": [ "Write_Latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Read Latency",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 48 },
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster_csv_filesystem",
     "select": [
      [
       { "params": [ "Read_Latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Shared FS Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_instance read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster_csv_filesystem",
     "select": [
      [
       { "params": [ "Read_Latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
     ]
    },
    {
     "alias": "$tag_instance write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster_csv_filesystem",
     "select": [
      [
       { "params": [ "Write_Latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
     ]
    }
   ]
  },
  {
   "title": "CSV Reads /sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT mean(\"Reads_persec\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s), \"instance\"",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSV Writes /sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT \"Disk_Transfers_persec\" FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" > '2') AND $timeFilter GROUP BY \"instance\", \"host\"",
     "select": [
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "DRT Dirty Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_instance in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Storage_Spaces_Drt",
     "query": "SELECT last(\"Dirty_Bytes\") FROM \"Storage_Spaces_Drt\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"instance\", \"host\" fill(none)",
     "select": [
      [
       { "params": [ "Dirty_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "DRT Limit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_instance in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Storage_Spaces_Drt",
     "query": "SELECT last(\"Dirty_Bytes\") FROM \"Storage_Spaces_Drt\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"instance\", \"host\" fill(none)",
     "select": [
      [
       { "params": [ "Limit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "DRT Synchronizing Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_instance in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Storage_Spaces_Drt",
     "query": "SELECT last(\"Dirty_Bytes\") FROM \"Storage_Spaces_Drt\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"instance\", \"host\" fill(none)",
     "select": [
      [
       { "params": [ "Synchronizing_Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}