{
 "title": "AzSHCI - VMFleet",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "SHOW TAG VALUES FROM \"win_system\" WITH KEY = \"clustername\""
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"win_system\" WITH KEY = \"host\""
   },
   {
    "name": "Interval",
    "label": "Interval",
    "query": "\"$__interval\",10s,30s,1m,5m,10m,15m,30m,1h"
   }
  ]
 },
 "panels": [
  { "title": "CSVFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IOPS Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Reads_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "IOPS Reads",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Reads_persec\") AS \"Reads\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ],
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "IOPS Writes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Writes_persec\") AS \"Writes\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ],
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "BW Total (MB/s)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Read_Bytes_persec\") + sum(\"Write_Bytes_persec\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "BW Reads (MB/s)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Read_Bytes_persec\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "BW Writes (MB/s)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Write_Bytes_persec\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Write_Bytes_persec\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Avg._sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Write_Bytes_persec\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Avg._sec/Write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "CSVFS - Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CSVFS  IOPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Reads_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Reads_persec\") AS \"Reads\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ],
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"Writes_persec\") AS \"Writes\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RDMA Network BW Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Sent",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RDMA_Activity",
     "query": "SELECT sum(\"RDMA_Outbound_Bytes_persec\") FROM \"RDMA_Activity\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "RDMA_Outbound_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Recieved",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "RDMA_Activity",
     "query": "SELECT mean(\"Bytes_Received_persec\") FROM \"hyperv_vmnet\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" =~ /_Network Adapter_/ AND \"instance\" =~ /^$vm_nic$/ AND $timeFilter GROUP BY time($__interval), \"instance\" fill(none)",
     "select": [
      [
       { "params": [ "RDMA_Inbound_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Latency Totals",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT mean(\"Read_Latency\") FROM \"cluster_csv_filesystem\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Avg._sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ],
      [
       { "params": [ "Avg._sec/Write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_filesystem",
     "query": "SELECT mean(\"Avg._sec/Read\") + mean(\"Avg._sec/Write\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Write_Latency" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Software Storage Bus (SSB) Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hit/Sec",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_caching",
       "query": "SELECT sum(\"Reads_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Cache_Hit_Reads_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Reads" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Miss/Sec",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_caching",
       "query": "SELECT sum(\"Reads_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Cache_Miss_Reads_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Reads" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Remap/Sec",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_stores_caching",
       "query": "SELECT sum(\"Reads_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Page_ReMap_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Reads" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Cache(MB/s)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_caching",
       "query": "SELECT sum(\"Cache_Populate_Bytes_persec\") + sum(\"Cache_Write_Bytes_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Cache_Populate_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "RdPop(MB/s)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_caching",
       "query": "SELECT sum(\"Cache_Populate_Bytes_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Cache_Populate_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "WrPop(MB/s)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_caching",
       "query": "SELECT sum(\"Cache_Write_Bytes_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Cache_Populate_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Destage(MB/s)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_caching",
       "query": "SELECT sum(\"Cache_Write_Bytes_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Destage_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Update(MB/s)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_stores_caching",
       "query": "SELECT sum(\"Cache_Write_Bytes_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Update_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Read Hits %",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Hits",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"Cache_Hit_Reads_persec\") / (sum(\"Cache_Hit_Reads_persec\") + sum(\"Cache_Miss_Reads_persec\"))  FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Read Misses %",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Misses",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"Cache_Miss_Reads_persec\") / (sum(\"Cache_Hit_Reads_persec\") + sum(\"Cache_Miss_Reads_persec\"))  FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total(Pgs)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 7 },
     "format": "kbytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_stores_caching",
       "query": "SELECT sum(\"Cache_Write_Bytes_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Cache_Pages" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "*16" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Standby(Pgs)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 7 },
     "format": "kbytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_stores_caching",
       "query": "SELECT sum(\"Cache_Write_Bytes_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Cache_Pages_Standby" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "*16" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Dirty(Pgs)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 7 },
     "format": "kbytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_stores_caching",
       "query": "SELECT sum(\"Cache_Write_Bytes_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Cache_Pages_Dirty" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "*16" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SSB Cache - Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CSVFS Cache Stores - Total Pgs (16kb page size)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "Total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_stores_caching",
       "query": "SELECT \"Cache_Pages_Dirty\" * 16 FROM \"cluster_csv_stores_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
       "select": [
        [
         { "params": [ "Cache_Pages" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "* 16" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "CSVFS Cache Stores - Standby Pgs (16kb page size)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "Total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_stores_caching",
       "query": "SELECT \"Cache_Pages_Dirty\" * 16 FROM \"cluster_csv_stores_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
       "select": [
        [
         { "params": [ "Cache_Pages_Standby" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "*16" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "CSVFS Cache Stores - Dirty Pages (16kb page size)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "Total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_stores_caching",
       "query": "SELECT \"Cache_Pages_Dirty\" * 16 FROM \"cluster_csv_stores_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
       "select": [
        [
         { "params": [ "Cache_Pages_Dirty" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "* 16" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "CSVFS Cache - Populate Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Populate Bytes",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_caching",
       "select": [
        [
         { "params": [ "Cache_Populate_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "CSVFS Cache - Update Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Update Bytes",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_stores_caching",
       "select": [
        [
         { "params": [ "Update_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "CSVFS Cache - Destage Bytes/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Destage Bytes/sec",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_caching",
       "select": [
        [
         { "params": [ "Destage_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Storage Bus Layer (SBL) Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "IOPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "IOPS Reads",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Read_persec\") AS \"Reads\" FROM \"cluster_csv_disk_caching\"  WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "IOPS Writes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Writes_persec\") AS \"Writes\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "BW Total (MB/s)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 22 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_disk_caching",
     "query": "SELECT sum(\"Read_-_Bytes_persec\") + sum(\"Write_-_Bytes_persec\") FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Read_-_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Reads (MB/s)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 22 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_disk_caching",
     "query": "SELECT sum(\"Read_-_Bytes_persec\") AS \"Reads\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Read_-_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Writes (MB/s)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 22 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_disk_caching",
     "query": "SELECT sum(\"Write_-_Bytes_persec\") FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Read_-_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 22 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_disk_caching",
     "query": "SELECT sum(\"Write_-_Bytes_persec\") FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Read_Latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 22 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_disk_caching",
     "query": "SELECT sum(\"Write_-_Bytes_persec\") FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Write_Latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "SBL Cache - Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_fs",
       "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Reads_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Reads" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"Read_persec\") AS \"Reads\" FROM \"cluster_csv_disk_caching\"  WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"Writes_persec\") AS \"Writes\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "BW (MB/s)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_disk_caching",
       "query": "SELECT sum(\"Read_-_Bytes_persec\") + sum(\"Write_-_Bytes_persec\") AS \"Total\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Read_-_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Reads" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"Read_-_Bytes_persec\") AS \"Reads\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"Write_-_Bytes_persec\") AS \"Writes\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "cluster_csv_disk_caching",
       "query": "SELECT mean(\"Read_Latency\") AS \"Reads\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "Read_Latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Reads" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Write_Latency\") AS \"Writes\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "SMB SRV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "IOPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_server_shares",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Data_Requests_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "IOPS Reads",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_server_shares",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Read_Requests_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "IOPS Writes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_server_shares",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Write_Requests_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Data BW (MB/s)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_server_shares",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Data_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Read",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_server_shares",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Write",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_server_shares",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Total BW (MB/s)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_server_shares",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Transferred_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Rcv",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_server_shares",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Received_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Snd",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 28 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_server_shares",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Sent_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "SMB SRV - Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_server_shares",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Data_Requests_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "\\\\*\\BlockShare$" }
     ]
    }
   ]
  },
  { "title": "Block Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CSVFS Block Cache - Valid %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - Valid % -",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_block_caching",
     "query": "SELECT sum(\"Cache_Size_-_Configured\") FROM \"cluster_csv_block_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Percent_Cache_Valid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Block Cache - Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_block_caching",
     "query": "SELECT sum(\"Cache_Size_-_Configured\") FROM \"cluster_csv_block_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Cache_Size_-_Current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Cache Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "CSVFS Cache - Usage %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 48 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Read Hits",
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT sum(\"Cache_Hit_Reads_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Cache_Usage_Percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Destaged at Low Priority %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 48 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT sum(\"Cache_Hit_Reads_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Destaged_At_Low_Pri._Percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache Stores - Pages Bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 48 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host",
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT \"Cache_Pages_Bytes\" FROM \"cluster_csv_stores_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\", \"instance\"",
     "select": [
      [
       { "params": [ "Cache_Pages_Bytes" ], "type": "field" },
       { "params": [ " * 24" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Usage Effficiency %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 50 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Read Hits",
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT sum(\"Cache_Hit_Reads_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Cache_Usage_Efficiency_Percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Destaged at Normal Priority %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 50 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT sum(\"Cache_Hit_Reads_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       {
        "params": [
         "Destaged_At_Normal_Pri._Percent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Bindings",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 50 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT \"Bindings_Active\" FROM \"cluster_csv_stores_caching\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\") AND $timeFilter",
     "select": [
      [
       { "params": [ "Bindings_Active" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}