{
 "title": "AzSHCI - Cache",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "SHOW TAG VALUES FROM \"win_system\" WITH KEY = \"clustername\""
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"win_system\" WITH KEY = \"host\""
   },
   {
    "name": "Interval",
    "label": "Interval",
    "query": "\"$__interval\",10s,30s,1m,5m,10m,15m,30m,1h"
   }
  ]
 },
 "panels": [
  { "title": "CSVFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CSVFS  IOPS Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Reads_persec\") AS \"Reads\", sum(\"Writes_persec\") AS \"Writes\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ],
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Reads_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Latency Totals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT mean(\"Read_Latency\") FROM \"cluster_csv_filesystem\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Avg._sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ],
      [
       { "params": [ "Avg._sec/Write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_filesystem",
     "query": "SELECT mean(\"Avg._sec/Read\") + mean(\"Avg._sec/Write\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Write_Latency" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Block Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CSVFS Block Cache - Valid %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - Valid % -",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_block_caching",
     "query": "SELECT sum(\"Cache_Size_-_Configured\") FROM \"cluster_csv_block_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Percent_Cache_Valid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Block Cache - Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_block_caching",
     "query": "SELECT sum(\"Cache_Size_-_Configured\") FROM \"cluster_csv_block_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Cache_Size_-_Current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Cache Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CSVFS Cache - Read Hits %",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"Cache_Hit_Reads_persec\") / (sum(\"Cache_Hit_Reads_persec\") + sum(\"Cache_Miss_Reads_persec\"))  FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Read Misses %",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 25 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Misses",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"Cache_Miss_Reads_persec\") / (sum(\"Cache_Hit_Reads_persec\") + sum(\"Cache_Miss_Reads_persec\"))  FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Usage %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 25 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Read Hits",
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT sum(\"Cache_Hit_Reads_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Cache_Usage_Percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache Stores - Pages Bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 25 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host",
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT \"Cache_Pages_Bytes\" FROM \"cluster_csv_stores_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\", \"instance\"",
     "select": [
      [
       { "params": [ "Cache_Pages_Bytes" ], "type": "field" },
       { "params": [ " * 24" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache Stores - Pages Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT \"Cache_Pages_Bytes\" FROM \"cluster_csv_stores_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\", \"instance\"",
     "select": [
      [
       { "params": [ "Cache_Pages_Bytes" ], "type": "field" },
       { "params": [ " * 4" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Usage Effficiency %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 27 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Read Hits",
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT sum(\"Cache_Hit_Reads_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Cache_Usage_Efficiency_Percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Bindings",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT \"Bindings_Active\" FROM \"cluster_csv_stores_caching\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\") AND $timeFilter",
     "select": [
      [
       { "params": [ "Bindings_Active" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Destaged at Low Priority %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 29 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT sum(\"Cache_Hit_Reads_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Destaged_At_Low_Pri._Percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Destaged at Normal Priority %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 31 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT sum(\"Cache_Hit_Reads_persec\") FROM \"cluster_csv_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       {
        "params": [
         "Destaged_At_Normal_Pri._Percent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CSVFS Cache - Read Misses Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Read Misses",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Cache_Miss_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Read Misses Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Cache_Miss_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Read Hits Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Total Read Hits",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Cache_Hit_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Read Hits Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host - Read Hits",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Cache_Hit_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Read IOPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Disk_Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Disk_Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Writes Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Cache Writes",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Cache_Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Write Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host - Writes Bytes",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Cache_Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Write IOPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Disk_Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Disk_Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Cache - SBL IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "SBL IOPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_disk_caching",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Read_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Cache - SBL IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_disk_caching",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s), \"host\"",
     "select": [
      [
       { "params": [ "Read_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Cache - SBL Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "SBL Read IOPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_disk_caching",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s), \"host\"",
     "select": [
      [
       { "params": [ "Read_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Cache - SBL Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_disk_caching",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s), \"host\"",
     "select": [
      [
       { "params": [ "Read_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Cache - SBL Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "SBL Write IOPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_disk_caching",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s), \"host\"",
     "select": [
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Cache - SBL Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_disk_caching",
     "query": "SELECT sum(\"Read_persec\") + sum(\"Writes_persec\") FROM \"cluster_csv_disk_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s), \"host\"",
     "select": [
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache Stores - Dirty Pages (16kb page size)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT \"Cache_Pages_Dirty\" * 16 FROM \"cluster_csv_stores_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "Cache_Pages_Dirty" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "* 16" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache Stores - Dirty Pages (16kb page size)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_stores_caching",
     "query": "SELECT \"Cache_Pages_Dirty\" * 16 FROM \"cluster_csv_stores_caching\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "Cache_Pages_Dirty" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "* 16" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Destage Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Destage Bytes/sec",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Destage_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Destage Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Destage_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Destage IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Destage IOPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Destage_Transfers_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Destage IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Destage_Transfers_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "% Disk Use - HDD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100 - mean(\"Percent_Idle_Time\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^([5-9]|1[012])$/) AND $timeFilter GROUP BY time(10s), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Disk Use - HDD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - ID: $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100 - mean(\"Percent_Idle_Time\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^([5-9]|1[012])$/) AND $timeFilter GROUP BY time(10s), \"host\", \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Disk Queue Length - HDD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"Current_Disk_Queue_Length\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^([5-9]|1[012])$/) AND $timeFilter GROUP BY time(10s), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Disk Queue Length - HDD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host - ID: $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Current_Disk_Queue_Length\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^([5-9]|1[012])$/) AND $timeFilter GROUP BY time(10s), \"host\", \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Disk Use - SSD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100 - mean(\"Percent_Idle_Time\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^([1-4])$/) AND $timeFilter GROUP BY time(10s), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Disk Use - SSD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 125 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - ID: $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100 - mean(\"Percent_Idle_Time\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^([1-4])$/) AND $timeFilter GROUP BY time(10s), \"host\", \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Disk Queue Length - SSD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"Current_Disk_Queue_Length\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^([1-4])$/) AND $timeFilter GROUP BY time(10s), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Disk Queue Length - SSD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host - ID: $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Current_Disk_Queue_Length\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^([1-4])$/) AND $timeFilter GROUP BY time(10s), \"host\", \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Populate Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Populate Bytes",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Cache_Populate_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Update Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Update Bytes",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_stores_caching",
     "select": [
      [
       { "params": [ "Update_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Populate Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Populate Bytes",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_caching",
     "select": [
      [
       { "params": [ "Cache_Populate_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Cache - Update Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 146 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Update Bytes",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_stores_caching",
     "select": [
      [
       { "params": [ "Update_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Space IOPS Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total IOPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT sum(\"Disk_Transfers_persec\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^(?:1(?:)[4-9])|(?:2[0-9])/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Disk_Transfers_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk IOPS Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total IOPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT sum(\"Disk_Transfers_persec\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" !~ /^(?:1(?:)[4-9])|(?:2[0-9])/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "Disk_Transfers_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}