{
 "title": "S2D",
 "tags": [
  "Hyper Converged",
  "Hyper-V",
  "Windows",
  "S2D"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "SHOW TAG VALUES FROM \"CSV_FS\" WITH KEY = \"clustername\""
   }
  ]
 },
 "panels": [
  {
   "title": "Notes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "content": "\n# TO DO\n\n- CSV chache\n- RDMA statistics (conn errors)\n- Network bandwidth\n\n\n\n"
    }
   ]
  },
  { "title": "Cluster Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Cluster Node status",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Name" ], "type": "tag" }
     ],
     "measurement": "socket_listener_STATUS",
     "query": "SELECT last(\"State\"),(\"StateString\") FROM \"socket_listener_STATUS\" WHERE (\"clustername\" = 'CLUSTER') GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Status Volumes",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "FriendlyName" ], "type": "tag" }
     ],
     "measurement": "socket_listener_PS",
     "query": "SELECT last(\"StorageEfficiency\"), last(\"HealthNum\"), last(\"PercentFree\") FROM \"socket_listener_PS\" WHERE (\"clustername\" =~ /^$Cluster$/) AND $timeFilter GROUP BY \"FriendlyName\"",
     "select": [
      [
       { "params": [ "StorageEfficiency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "HealthNum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "PercentFree" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Host Latency",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 2 },
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "CSV_FS",
     "select": [
      [
       { "params": [ "Avg._sec/Read" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "CSV_FS",
     "select": [
      [
       { "params": [ "Avg._sec/Write" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ]
    }
   ]
  },
  { "title": "CSV Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "IO History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "CSV_FS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Value\") FROM \"socket_listener_CLUSTERPERF\" WHERE (\"MetricId\" = 'Volume.IOPS.Read,Volume=S2D-N1') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "CSV_FS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Value\") FROM \"socket_listener_CLUSTERPERF\" WHERE (\"MetricId\" = 'Volume.IOPS.Write,Volume=S2D-N1') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "Writes_persec" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CSV Bandwith History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "write",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Write_Bytes_persec\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N1') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "read",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Write_Bytes_persec\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N2') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Read",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ]
    }
   ]
  },
  {
   "title": "Write",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "select": [
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency S2D-N2",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "select": [
      [
       { "params": [ "Avg._sec/Write" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ]
    }
   ]
  },
  {
   "title": "Read Latency S2D-N2",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "select": [
      [
       { "params": [ "Avg._sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ]
    }
   ]
  },
  { "title": "VM performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "VM IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Mountpoint" ], "type": "tag" }
     ],
     "measurement": "socket_listener_QOS",
     "select": [
      [
       { "params": [ "IOPS" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "VM Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Mountpoint" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_QOS",
     "select": [
      [
       { "params": [ "Bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "VM Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Mountpoint" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_QOS",
     "select": [
      [
       { "params": [ "Latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  { "title": "S2D health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Storage Jobs",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "socket_listener_JOBS",
     "query": "SELECT last(\"PercentComplete\") FROM \"socket_listener_JOBS\" WHERE $timeFilter AND  (\"clustername\" =~ /^$Cluster$/) AND \"PercentComplete\" < 100 GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "PercentComplete" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  }
 ]
}