{
 "title": "S2D",
 "tags": [
  "Hyper Converged",
  "Hyper-V",
  "Windows",
  "S2D"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "S2D-N1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_STATUS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"State\") FROM \"HC\".\"socket_listener_STATUS\" WHERE (\"Name\" = 'S2D-N1') ",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "S2D-N1" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S2D-N2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_STATUS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"State\") FROM \"HC\".\"socket_listener_STATUS\" WHERE (\"Name\" = 'S2D-N2')",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "S2D-N2" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IO History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Read S2D-N1",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Value\") FROM \"socket_listener_CLUSTERPERF\" WHERE (\"MetricId\" = 'Volume.IOPS.Read,Volume=S2D-N1') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S2D-N1" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Read S2D-N2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Value\") FROM \"socket_listener_CLUSTERPERF\" WHERE (\"MetricId\" = 'Volume.IOPS.Read,Volume=S2D-N2') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S2D-N2" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Write S2D-N2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Value\") FROM \"socket_listener_CLUSTERPERF\" WHERE (\"MetricId\" = 'Volume.IOPS.Write,Volume=S2D-N1') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S2D-N2" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Write S2D-N1",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Value\") FROM \"socket_listener_CLUSTERPERF\" WHERE (\"MetricId\" = 'Volume.IOPS.Write,Volume=S2D-N1') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S2D-N1" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bandwith History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "S2D-N1 W",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Write_Bytes_persec\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N1') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "S2D-N1" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "S2D-N1 R",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Write_Bytes_persec\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N2') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "S2D-N1" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "S2D-N2 R",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Read_Bytes_persec\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N1') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "S2D-N2" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "S2D-N2 W",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Read_Bytes_persec\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N1') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "S2D-N2" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Latency History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Read S2D-N1",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "select": [
      [
       { "params": [ "Avg._sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S2D-N1" }
     ]
    },
    {
     "alias": "Read S2D-N2",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "select": [
      [
       { "params": [ "Avg._sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S2D-N2" }
     ]
    },
    {
     "alias": "Write S2D-N1",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "select": [
      [
       { "params": [ "Avg._sec/Write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S2D-N1" }
     ]
    },
    {
     "alias": "Write S2D-N2",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "select": [
      [
       { "params": [ "Avg._sec/Write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S2D-N2" }
     ]
    }
   ]
  },
  {
   "title": "Read S2D-N1",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "socket_listener_CLUSTERPERF",
     "query": "SELECT last(\"Reads_persec\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N1' AND \"instance\" = 'S2D-N1') ",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "MetricId", "operator": "=", "value": "Volume.IOPS.Read,Volume=S2D-N1" }
     ]
    }
   ]
  },
  {
   "title": "Write S2D-N1",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_CLUSTERPERF",
     "query": "SELECT last(\"Writes_persec\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N1' AND \"instance\" = 'S2D-N1') ",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "MetricId",
       "operator": "=",
       "value": "Volume.IOPS.Write,Volume=S2D-N1"
      }
     ]
    }
   ]
  },
  {
   "title": "Read Latency S2D-N1",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_CLUSTERPERF",
     "query": "SELECT last(\"Avg._sec/Read\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N1' AND \"instance\" = 'S2D-N1') ",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "MetricId",
       "operator": "=",
       "value": "Volume.Latency.Read,Volume=S2D-N1"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Latency S2D-N1",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_CLUSTERPERF",
     "query": "SELECT last(\"Avg._sec/Write\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N1' AND \"instance\" = 'S2D-N1') ",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "MetricId",
       "operator": "=",
       "value": "Volume.Latency.Write,Volume=S2D-N1"
      }
     ]
    }
   ]
  },
  {
   "title": "IO per Host",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_disk",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Reads_persec_Total\"), last(\"Writes_persec_Total\") FROM \"Total_persec_Total\" GROUP BY \"host\" ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Read S2D-N2",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_CLUSTERPERF",
     "query": "SELECT last(\"Reads_persec\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N2' AND \"instance\" = 'S2D-N2') ",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "MetricId", "operator": "=", "value": "Volume.IOPS.Read,Volume=S2D-N2" }
     ]
    }
   ]
  },
  {
   "title": "Write S2D-N2",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "query": "SELECT last(\"Writes_persec\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N2' AND \"instance\" = 'S2D-N2') ",
     "select": [
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "S2D-N2" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "S2D-N2" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency S2D-N2",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_CLUSTERPERF",
     "query": "SELECT last(\"Avg._sec/Write\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N2' AND \"instance\" = 'S2D-N2') ",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "MetricId",
       "operator": "=",
       "value": "Volume.Latency.Write,Volume=S2D-N2"
      }
     ]
    }
   ]
  },
  {
   "title": "Read Latency S2D-N2",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CSV_FS",
     "query": "SELECT last(\"Avg._sec/Read\") FROM \"CSV_FS\" WHERE (\"host\" = 'S2D-N2' AND \"instance\" = 'S2D-N2') ",
     "select": [
      [
       { "params": [ "Avg._sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "S2D-N2" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "S2D-N2" }
     ]
    }
   ]
  },
  {
   "title": "CPU S2D-N1",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hv_cpu",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Percent_Total_Run_Time\") FROM \"HC\".\"hv_cpu\" WHERE (\"host\" = 'S2D-N1') ",
     "select": [
      [
       { "params": [ "Percent_Total_Run_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "S2D-N1" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory S2D-N1",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_CLUSTERPERF",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Percent_Committed_Bytes_In_Use\") FROM \"win_system\" WHERE (\"host\" = 'S2D-N1') ",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "S2D-N1" },
      {
       "condition": "AND",
       "key": "MetricId",
       "operator": "=",
       "value": "ClusterNode.Memory.Usage,ClusterNode=S2D-N1"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status Volumes",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "FriendlyName" ], "type": "tag" }
     ],
     "measurement": "socket_listener_PS",
     "query": "SELECT last(\"StorageEfficiency\"), last(\"HealthNum\"), 100- last(\"PercentFree\") FROM \"socket_listener_PS\" WHERE $timeFilter GROUP BY \"FriendlyName\"",
     "select": [
      [
       { "params": [ "StorageEfficiency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "HealthNum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "PercentFree" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU  S2D-N2",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "measurement": "hv_cpu",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "Percent_Total_Run_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "S2D-N2" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory S2D-N2",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"Percent_Committed_Bytes_In_Use\") FROM \"win_system\" WHERE (\"host\" = 'S2D-N2')",
     "select": [
      [
       { "params": [ "Percent_Committed_Bytes_In_Use" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "S2D-N2" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VM IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Vol S2D-N1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_QOS",
     "select": [
      [
       { "params": [ "IOPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Mountpoint", "operator": "=", "value": "S2D-N1" }
     ]
    },
    {
     "alias": "Vol S2D-N2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_QOS",
     "select": [
      [
       { "params": [ "IOPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Mountpoint", "operator": "=", "value": "S2D-N2" }
     ]
    }
   ]
  },
  {
   "title": "VM Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Vol S2D-N1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_QOS",
     "select": [
      [
       { "params": [ "Bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Mountpoint", "operator": "=", "value": "S2D-N1" }
     ]
    },
    {
     "alias": "Vol S2D-N2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_QOS",
     "select": [
      [
       { "params": [ "Bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Mountpoint", "operator": "=", "value": "S2D-N2" }
     ]
    }
   ]
  },
  {
   "title": "VM Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Vol S2D-N1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_QOS",
     "select": [
      [
       { "params": [ "Latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Mountpoint", "operator": "=", "value": "S2D-N1" }
     ]
    },
    {
     "alias": "Vol S2D-N2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket_listener_QOS",
     "select": [
      [
       { "params": [ "Latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Mountpoint", "operator": "=", "value": "S2D-N2" }
     ]
    }
   ]
  },
  {
   "title": "Storage Jobs",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "socket_listener_JOBS",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"PercentComplete\") FROM \"HC\".\"socket_listener_JOBS\" WHERE $timeFilter AND  \"PercentComplete\" < 100 GROUP BY \"name\" ",
     "select": [
      [
       { "params": [ "PercentComplete" ], "type": "field" }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}