name: Create prerelease

defaults:
  run:
    shell: powershell

on:
  push:
    paths: 
      - 'Scripts/**'
      - 'Tools/**'
    branches: [ dev ]

jobs:
  new-prerelease:
    name: Create prerelease
    if: "!contains(github.event.head_commit.message, '[no release]')"
    runs-on: windows-2019
    permissions:
      # needed to create a release
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build scripts 
        id: build
        shell: powershell
        run: |
          ./build.ps1 -Version dev
          $filename = "mslab_dev-$((Get-Date -Format "yyyyMMdd")).zip"
          mv ./Release.zip $filename
          echo "filename=$filename" >> $env:GITHUB_OUTPUT
      - name: Delete current dev prerelease
        uses: cb80/delrel@latest
        with:
          tag: dev
      - name: Create new dev prerelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev
          name: dev branch preview
          generate_release_notes: true
          prerelease: true
          files: |
            ${{ steps.build.outputs.filename }}
            Output/Tools/*.ps1
